/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.worldstudiosbigjavaaddon.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.worldstudiosbigjavaaddon.BigAddonMod;

@EventBusSubscriber
public class BigAddonModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, BigAddonMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> EXPLOSIVES = REGISTRY.register("explosives",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.big_addon.explosives")).icon(() -> new ItemStack(Blocks.TNT)).displayItems((parameters, tabData) -> {
				tabData.accept(BigAddonModItems.DINAMITE.get());
				tabData.accept(BigAddonModBlocks.IGNYITE.get().asItem());
			}).withSearchBar().build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
			tabData.accept(BigAddonModItems.COAL_PICKAXE.get());
			tabData.accept(BigAddonModItems.ACID_FLUID_BUCKET.get());
			tabData.accept(BigAddonModItems.URAINIUM_BLADE.get());
			tabData.accept(BigAddonModItems.URAINIUM_PICKAXE.get());
			tabData.accept(BigAddonModItems.URAINIUM_SHIELD.get());
			tabData.accept(BigAddonModItems.ORACLE.get());
			tabData.accept(BigAddonModItems.FORGIUM_MULTITOOL.get());
			tabData.accept(BigAddonModItems.TITAN_TOOL_PICKAXE.get());
			tabData.accept(BigAddonModItems.TITAN_TOOL_AXE.get());
			tabData.accept(BigAddonModItems.SPARKLE_PICKAXE.get());
			tabData.accept(BigAddonModItems.SPARKLE_AXE.get());
			tabData.accept(BigAddonModItems.ENERGY_DETECTOR.get());
			tabData.accept(BigAddonModItems.ANDOR_PICKAXE.get());
			tabData.accept(BigAddonModItems.ANDOR_AXE.get());
			tabData.accept(BigAddonModItems.ANDOR_SHOVEL.get());
			tabData.accept(BigAddonModItems.ANDOR_HOE.get());
			tabData.accept(BigAddonModItems.DIRT_TOOL_PICKAXE.get());
			tabData.accept(BigAddonModItems.DIRT_TOOL_AXE.get());
			tabData.accept(BigAddonModItems.DIRT_TOOL_SHOVEL.get());
			tabData.accept(BigAddonModItems.DIRT_TOOL_HOE.get());
			tabData.accept(BigAddonModItems.ANDESITE_PICKAXE.get());
			tabData.accept(BigAddonModItems.ANDESITE_AXE.get());
			tabData.accept(BigAddonModItems.ANDESITE_SHOVEL.get());
			tabData.accept(BigAddonModItems.ANDESITE_HOE.get());
			tabData.accept(BigAddonModItems.BLAZITE_PICKAXE.get());
			tabData.accept(BigAddonModItems.BLAZITE_AXE.get());
			tabData.accept(BigAddonModItems.BLAZITE_SHOVEL.get());
			tabData.accept(BigAddonModItems.BLAZITE_HOE.get());
			tabData.accept(BigAddonModItems.GRANITE_PICKAXE.get());
			tabData.accept(BigAddonModItems.GRANITE_AXE.get());
			tabData.accept(BigAddonModItems.GRANITE_SHOVEL.get());
			tabData.accept(BigAddonModItems.GRANITE_HOE.get());
			tabData.accept(BigAddonModItems.WOOL_PICKAXE.get());
			tabData.accept(BigAddonModItems.WOOL_AXE.get());
			tabData.accept(BigAddonModItems.WOOL_SHOVEL.get());
			tabData.accept(BigAddonModItems.WOOL_HOE.get());
			tabData.accept(BigAddonModItems.CAREFREE.get());
			tabData.accept(BigAddonModItems.TRASH_BAG.get());
			tabData.accept(BigAddonModItems.DARK_BAT_SHEILD.get());
			tabData.accept(BigAddonModItems.NACOR_PICKAXE.get());
			tabData.accept(BigAddonModItems.NACOR_AXE.get());
			tabData.accept(BigAddonModItems.NACOR_SHOVEL.get());
			tabData.accept(BigAddonModItems.NACOR_HOE.get());
			tabData.accept(BigAddonModItems.SKELETON_PICKAXE.get());
			tabData.accept(BigAddonModItems.SKELETON_AXE.get());
			tabData.accept(BigAddonModItems.SKELETON_SHOVEL.get());
			tabData.accept(BigAddonModItems.SKELETON_HOE.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_PICKAXE.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_AXE.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_SHOVEL.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_HOE.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_PICKAXE.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_AXE.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_SHOVEL.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_HOE.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_PICKAXE.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_AXE.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_SHOVEL.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_HOE.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_PICKAXE.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_AXE.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_SHOVEL.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_HOE.get());
			tabData.accept(BigAddonModItems.DARK_PARTICLE_ITEM.get());
			tabData.accept(BigAddonModItems.STEEL_TOOL_PICKAXE.get());
			tabData.accept(BigAddonModItems.STEEL_TOOL_AXE.get());
			tabData.accept(BigAddonModItems.STEEL_TOOL_SHOVEL.get());
			tabData.accept(BigAddonModItems.STEEL_TOOL_HOE.get());
			tabData.accept(BigAddonModItems.REFINED_FLINT_AND_STEEL.get());
			tabData.accept(BigAddonModItems.THE_WILL_OF_RIGHTS.get());
			tabData.accept(BigAddonModItems.BRANITE_LUNGE.get());
			tabData.accept(BigAddonModItems.STONE_LUNGE.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_PICKAXE.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_AXE.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_SHOVEL.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_HOE.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_LUNGE.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.COMBAT) {
			tabData.accept(BigAddonModItems.ENDER_HELMET_HELMET.get());
			tabData.accept(BigAddonModItems.ACID_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.ACID_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.ACID_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.ACID_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.DINAMITE.get());
			tabData.accept(BigAddonModItems.DIRT_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.DIRT_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.DIRT_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.DIRT_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.TITAN_ARMOR_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.TITAN_ARMOR_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.TITAN_ARMOR_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.TITAN_ARMOR_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.TITAN_TOOL_SWORD.get());
			tabData.accept(BigAddonModItems.SPARKLE_SWORD.get());
			tabData.accept(BigAddonModItems.ANDOR_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.ANDOR_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.ANDOR_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.ANDOR_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.ANDOR_SWORD.get());
			tabData.accept(BigAddonModItems.DIRT_TOOL_SWORD.get());
			tabData.accept(BigAddonModItems.ANDESITE_SWORD.get());
			tabData.accept(BigAddonModItems.GRANITE_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.GRANITE_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.GRANITE_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.GRANITE_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.BLAZITE_SWORD.get());
			tabData.accept(BigAddonModItems.BLAZITE_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.BLAZITE_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.BLAZITE_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.BLAZITE_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.STONE_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.STONE_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.STONE_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.STONE_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.WOOL_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.WOOL_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.WOOL_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.WOOL_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.ANDESITE_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.ANDESITE_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.ANDESITE_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.ANDESITE_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.GRANITE_SWORD.get());
			tabData.accept(BigAddonModItems.WOOL_SWORD.get());
			tabData.accept(BigAddonModItems.BRAIN_ARMOR_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.BRAIN_ARMOR_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.BRAIN_ARMOR_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.BRAIN_ARMOR_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.NACOR_SWORD.get());
			tabData.accept(BigAddonModItems.SWORD_OF_THE_FROZEN_WARRIOR.get());
			tabData.accept(BigAddonModItems.SKELETON_SWORD.get());
			tabData.accept(BigAddonModItems.SKELETON_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.SKELETON_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.SKELETON_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.SKELETON_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_SWORD.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.COMMAND_BLOCK_SWORD.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.CHAIN_COMMAND_BLOCK_SWORD.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.REPEATING_COMMAND_BLOCK_SWORD.get());
			tabData.accept(BigAddonModItems.BRICK_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.BRICK_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.BRICK_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.BRICK_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.RESIN_BRICK_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.RESIN_BRICK_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.RESIN_BRICK_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.RESIN_BRICK_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.DEEPSLATE_BRICK_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.DEEPSLATE_BRICK_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.DEEPSLATE_BRICK_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.DEEPSLATE_BRICK_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.STEEL_ARMOR_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.STEEL_ARMOR_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.STEEL_ARMOR_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.STEEL_ARMOR_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.STEEL_TOOL_SWORD.get());
			tabData.accept(BigAddonModItems.BRANITE_LUNGE.get());
			tabData.accept(BigAddonModItems.STONE_LUNGE.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_SWORD.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_ARMOR_HELMET.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_ARMOR_CHESTPLATE.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_ARMOR_LEGGINGS.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_ARMOR_BOOTS.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_LUNGE.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {
			tabData.accept(BigAddonModBlocks.WASTE_BLOCK.get().asItem());
			tabData.accept(BigAddonModBlocks.CAPSULE.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_WOOD.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_LOG.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_PLANKS.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_STAIRS.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_SLAB.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_FENCE.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_FENCE_GATE.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_PRESSURE_PLATE.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_BUTTON.get().asItem());
			tabData.accept(BigAddonModBlocks.BLAZITE_ORE.get().asItem());
			tabData.accept(BigAddonModBlocks.BLAZITE_BLOCK.get().asItem());
			tabData.accept(BigAddonModBlocks.BRAIN.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_WOOD.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_LOG.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_PLANKS.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_STAIRS.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_SLAB.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_FENCE.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_FENCE_GATE.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_PRESSURE_PLATE.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_BUTTON.get().asItem());
			tabData.accept(BigAddonModBlocks.IGNIGHTIUM_ORE.get().asItem());
			tabData.accept(BigAddonModBlocks.IGNIGHTIUM_BLOCK.get().asItem());
			tabData.accept(BigAddonModBlocks.ICE_PILLAR.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.NATURAL_BLOCKS) {
			tabData.accept(BigAddonModBlocks.WASTE_STONE.get().asItem());
			tabData.accept(BigAddonModBlocks.WASTE_LOG.get().asItem());
			tabData.accept(BigAddonModBlocks.WASTE_LEAVES.get().asItem());
			tabData.accept(BigAddonModBlocks.URAINIUM_CHUNK.get().asItem());
			tabData.accept(BigAddonModBlocks.GRAVITE.get().asItem());
			tabData.accept(BigAddonModBlocks.SEMITE.get().asItem());
			tabData.accept(BigAddonModBlocks.FORGIUM_ORE.get().asItem());
			tabData.accept(BigAddonModBlocks.HEVORE.get().asItem());
			tabData.accept(BigAddonModBlocks.BLOCK_OF_SPARKLES.get().asItem());
			tabData.accept(BigAddonModBlocks.GYRULE_ORE.get().asItem());
			tabData.accept(BigAddonModBlocks.ANDOR_LEAVES.get().asItem());
			tabData.accept(BigAddonModBlocks.YELLOW_DIRT.get().asItem());
			tabData.accept(BigAddonModBlocks.YELLOW_GRASS_BLOCK.get().asItem());
			tabData.accept(BigAddonModBlocks.GREEN_SAND.get().asItem());
			tabData.accept(BigAddonModBlocks.GREEN_SANDSTONE.get().asItem());
			tabData.accept(BigAddonModBlocks.SMOOTH_GREEN_SANDSTONE.get().asItem());
			tabData.accept(BigAddonModBlocks.FROZEN_GRAVITE.get().asItem());
			tabData.accept(BigAddonModBlocks.NACOR_LEAVES.get().asItem());
			tabData.accept(BigAddonModBlocks.ICEY_GRASS.get().asItem());
			tabData.accept(BigAddonModBlocks.DARK_FLOWER.get().asItem());
			tabData.accept(BigAddonModBlocks.BRANITE_ORE.get().asItem());
			tabData.accept(BigAddonModBlocks.AMETHESIUM_ORE.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.FOOD_AND_DRINKS) {
			tabData.accept(BigAddonModItems.WASTE.get());
			tabData.accept(BigAddonModItems.FERTILIZED_SUGAR.get());
			tabData.accept(BigAddonModItems.COOKIE.get());
			tabData.accept(BigAddonModItems.SUGAR_COOKIE.get());
			tabData.accept(BigAddonModItems.APPLE_PIE.get());
			tabData.accept(BigAddonModItems.BRAIN_FOOD.get());
			tabData.accept(BigAddonModItems.BRAIN_FLUID_BUCKET.get());
			tabData.accept(BigAddonModItems.DARK_COOKIE.get());
			tabData.accept(BigAddonModItems.CUBE_ESSENCE.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.INGREDIENTS) {
			tabData.accept(BigAddonModItems.URAINIUM_PEICE.get());
			tabData.accept(BigAddonModItems.URAINIUM_INGOT.get());
			tabData.accept(BigAddonModItems.FORGIUM.get());
			tabData.accept(BigAddonModItems.TITAN_HEART.get());
			tabData.accept(BigAddonModItems.TITAN_INGOT.get());
			tabData.accept(BigAddonModBlocks.BLOCK_OF_SPARKLES.get().asItem());
			tabData.accept(BigAddonModItems.SPARKLES.get());
			tabData.accept(BigAddonModItems.FAIRY_HEART.get());
			tabData.accept(BigAddonModItems.GYRULE_CRYSTAL.get());
			tabData.accept(BigAddonModItems.FERTILIZED_SUGAR.get());
			tabData.accept(BigAddonModItems.BLAZITE.get());
			tabData.accept(BigAddonModItems.DARK_BAT_WING.get());
			tabData.accept(BigAddonModItems.YETI_HEART.get());
			tabData.accept(BigAddonModItems.ICE_DRAGON_HEART.get());
			tabData.accept(BigAddonModItems.IGNIGHTIUM_INGOT.get());
			tabData.accept(BigAddonModItems.DARK_SPLATTER.get());
			tabData.accept(BigAddonModItems.STEEL.get());
			tabData.accept(BigAddonModItems.CAPSTEEL.get());
			tabData.accept(BigAddonModItems.MOLTEN_METAL.get());
			tabData.accept(BigAddonModItems.VERY_MOLTEN_METAL.get());
			tabData.accept(BigAddonModBlocks.BLOCK_OF_FLINT.get().asItem());
			tabData.accept(BigAddonModItems.WARTED_EMERALD.get());
			tabData.accept(BigAddonModItems.BRANITE.get());
			tabData.accept(BigAddonModItems.AMETHESIUM_INGOT.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS) {
			tabData.accept(BigAddonModBlocks.MOLDELER.get().asItem());
			tabData.accept(BigAddonModBlocks.IGNYITE.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.REDSTONE_BLOCKS) {
			tabData.accept(BigAddonModBlocks.CAPSULED_REDSTONE_BLOCK.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.SPAWN_EGGS) {
			tabData.accept(BigAddonModItems.LONG_ZOMBIE_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.TITAN_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.FAIRY_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.PROD_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.SUGAR_ENTITY_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.BIRD_BRAIN_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.DARK_BAT_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.THIEF_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.RADIANT_ZOMBIE_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.YETI_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.ICE_DRAGON_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.MASTER_OF_THE_DARK_ARTS_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.DARK_PHANTOM_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.WALKING_CHEST_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.BULL_SPAWN_EGG.get());
			tabData.accept(BigAddonModItems.CUBER_SPAWN_EGG.get());
		}
	}
}