/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.worldstudiosbigjavaaddon.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.worldstudiosbigjavaaddon.item.inventory.TrashBagInventoryCapability;
import net.mcreator.worldstudiosbigjavaaddon.item.*;
import net.mcreator.worldstudiosbigjavaaddon.BigAddonMod;

import java.util.function.Function;

@EventBusSubscriber
public class BigAddonModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(BigAddonMod.MODID);
	public static final DeferredItem<Item> COAL_PICKAXE;
	public static final DeferredItem<Item> ENDER_HELMET_HELMET;
	public static final DeferredItem<Item> ACID_ARMOR_HELMET;
	public static final DeferredItem<Item> ACID_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ACID_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ACID_ARMOR_BOOTS;
	public static final DeferredItem<Item> ACID_FLUID_BUCKET;
	public static final DeferredItem<Item> DINAMITE;
	public static final DeferredItem<Item> WASTE_BLOCK;
	public static final DeferredItem<Item> WASTE_STONE;
	public static final DeferredItem<Item> WASTE_LOG;
	public static final DeferredItem<Item> WASTE_LEAVES;
	public static final DeferredItem<Item> WASTE;
	public static final DeferredItem<Item> URAINIUM_CHUNK;
	public static final DeferredItem<Item> URAINIUM_PEICE;
	public static final DeferredItem<Item> URAINIUM_INGOT;
	public static final DeferredItem<Item> URAINIUM_BLADE;
	public static final DeferredItem<Item> URAINIUM_PICKAXE;
	public static final DeferredItem<Item> URAINIUM_SHIELD;
	public static final DeferredItem<Item> DIRT_ARMOR_HELMET;
	public static final DeferredItem<Item> DIRT_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DIRT_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DIRT_ARMOR_BOOTS;
	public static final DeferredItem<Item> GRAVITE;
	public static final DeferredItem<Item> ORACLE;
	public static final DeferredItem<Item> SEMITE;
	public static final DeferredItem<Item> FORGIUM_ORE;
	public static final DeferredItem<Item> FORGIUM;
	public static final DeferredItem<Item> FORGIUM_MULTITOOL;
	public static final DeferredItem<Item> MOLDELER;
	public static final DeferredItem<Item> CAPSULE;
	public static final DeferredItem<Item> CAPSULED_REDSTONE_BLOCK;
	public static final DeferredItem<Item> LONG_ZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> TITAN_SPAWN_EGG;
	public static final DeferredItem<Item> TITAN_HEART;
	public static final DeferredItem<Item> TITAN_INGOT;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_HELMET;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TITAN_ARMOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> HEVORE;
	public static final DeferredItem<Item> TITAN_TOOL_PICKAXE;
	public static final DeferredItem<Item> TITAN_TOOL_AXE;
	public static final DeferredItem<Item> TITAN_TOOL_SWORD;
	public static final DeferredItem<Item> FAIRY_SPAWN_EGG;
	public static final DeferredItem<Item> BLOCK_OF_SPARKLES;
	public static final DeferredItem<Item> PROD_SPAWN_EGG;
	public static final DeferredItem<Item> PROD_MISSLE_ITEM;
	public static final DeferredItem<Item> SPARKLES;
	public static final DeferredItem<Item> FAIRY_HEART;
	public static final DeferredItem<Item> SPARKLE_PICKAXE;
	public static final DeferredItem<Item> SPARKLE_AXE;
	public static final DeferredItem<Item> SPARKLE_SWORD;
	public static final DeferredItem<Item> ENERGY_DETECTOR;
	public static final DeferredItem<Item> GYRULE_ORE;
	public static final DeferredItem<Item> GYRULE_CRYSTAL;
	public static final DeferredItem<Item> ANDOR_WOOD;
	public static final DeferredItem<Item> ANDOR_LOG;
	public static final DeferredItem<Item> ANDOR_PLANKS;
	public static final DeferredItem<Item> ANDOR_LEAVES;
	public static final DeferredItem<Item> ANDOR_STAIRS;
	public static final DeferredItem<Item> ANDOR_SLAB;
	public static final DeferredItem<Item> ANDOR_FENCE;
	public static final DeferredItem<Item> ANDOR_FENCE_GATE;
	public static final DeferredItem<Item> ANDOR_PRESSURE_PLATE;
	public static final DeferredItem<Item> ANDOR_BUTTON;
	public static final DeferredItem<Item> ANDOR_ARMOR_HELMET;
	public static final DeferredItem<Item> ANDOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ANDOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ANDOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> ANDOR_PICKAXE;
	public static final DeferredItem<Item> ANDOR_AXE;
	public static final DeferredItem<Item> ANDOR_SWORD;
	public static final DeferredItem<Item> ANDOR_SHOVEL;
	public static final DeferredItem<Item> ANDOR_HOE;
	public static final DeferredItem<Item> SUGAR_ENTITY_SPAWN_EGG;
	public static final DeferredItem<Item> FERTILIZED_SUGAR;
	public static final DeferredItem<Item> DIRT_TOOL_PICKAXE;
	public static final DeferredItem<Item> DIRT_TOOL_AXE;
	public static final DeferredItem<Item> DIRT_TOOL_SWORD;
	public static final DeferredItem<Item> DIRT_TOOL_SHOVEL;
	public static final DeferredItem<Item> DIRT_TOOL_HOE;
	public static final DeferredItem<Item> ANDESITE_PICKAXE;
	public static final DeferredItem<Item> ANDESITE_AXE;
	public static final DeferredItem<Item> ANDESITE_SWORD;
	public static final DeferredItem<Item> ANDESITE_SHOVEL;
	public static final DeferredItem<Item> ANDESITE_HOE;
	public static final DeferredItem<Item> GRANITE_ARMOR_HELMET;
	public static final DeferredItem<Item> GRANITE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> GRANITE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> GRANITE_ARMOR_BOOTS;
	public static final DeferredItem<Item> YELLOW_DIRT;
	public static final DeferredItem<Item> YELLOW_GRASS_BLOCK;
	public static final DeferredItem<Item> BLAZITE;
	public static final DeferredItem<Item> BLAZITE_ORE;
	public static final DeferredItem<Item> BLAZITE_BLOCK;
	public static final DeferredItem<Item> BLAZITE_PICKAXE;
	public static final DeferredItem<Item> BLAZITE_AXE;
	public static final DeferredItem<Item> BLAZITE_SWORD;
	public static final DeferredItem<Item> BLAZITE_SHOVEL;
	public static final DeferredItem<Item> BLAZITE_HOE;
	public static final DeferredItem<Item> BLAZITE_ARMOR_HELMET;
	public static final DeferredItem<Item> BLAZITE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BLAZITE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BLAZITE_ARMOR_BOOTS;
	public static final DeferredItem<Item> BRAIN;
	public static final DeferredItem<Item> BIRD_BRAIN_SPAWN_EGG;
	public static final DeferredItem<Item> STONE_ARMOR_HELMET;
	public static final DeferredItem<Item> STONE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> STONE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> STONE_ARMOR_BOOTS;
	public static final DeferredItem<Item> COOKIE;
	public static final DeferredItem<Item> SUGAR_COOKIE;
	public static final DeferredItem<Item> WOOL_ARMOR_HELMET;
	public static final DeferredItem<Item> WOOL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> WOOL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> WOOL_ARMOR_BOOTS;
	public static final DeferredItem<Item> ANDESITE_ARMOR_HELMET;
	public static final DeferredItem<Item> ANDESITE_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ANDESITE_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ANDESITE_ARMOR_BOOTS;
	public static final DeferredItem<Item> GRANITE_PICKAXE;
	public static final DeferredItem<Item> GRANITE_AXE;
	public static final DeferredItem<Item> GRANITE_SWORD;
	public static final DeferredItem<Item> GRANITE_SHOVEL;
	public static final DeferredItem<Item> GRANITE_HOE;
	public static final DeferredItem<Item> WOOL_PICKAXE;
	public static final DeferredItem<Item> WOOL_AXE;
	public static final DeferredItem<Item> WOOL_SWORD;
	public static final DeferredItem<Item> WOOL_SHOVEL;
	public static final DeferredItem<Item> WOOL_HOE;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_HELMET;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BRAIN_ARMOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> CAREFREE;
	public static final DeferredItem<Item> HEROIC_DIAMOND;
	public static final DeferredItem<Item> TRASH_BAG;
	public static final DeferredItem<Item> DARK_BAT_SPAWN_EGG;
	public static final DeferredItem<Item> DARK_BAT_WING;
	public static final DeferredItem<Item> DARK_BAT_SHEILD;
	public static final DeferredItem<Item> THIEF_SPAWN_EGG;
	public static final DeferredItem<Item> APPLE_PIE;
	public static final DeferredItem<Item> GREEN_SAND;
	public static final DeferredItem<Item> GREEN_SANDSTONE;
	public static final DeferredItem<Item> SMOOTH_GREEN_SANDSTONE;
	public static final DeferredItem<Item> BRAIN_FOOD;
	public static final DeferredItem<Item> RADIANT_ZOMBIE_SPAWN_EGG;
	public static final DeferredItem<Item> FROZEN_GRAVITE;
	public static final DeferredItem<Item> NACOR_WOOD;
	public static final DeferredItem<Item> NACOR_LOG;
	public static final DeferredItem<Item> NACOR_PLANKS;
	public static final DeferredItem<Item> NACOR_LEAVES;
	public static final DeferredItem<Item> NACOR_STAIRS;
	public static final DeferredItem<Item> NACOR_SLAB;
	public static final DeferredItem<Item> NACOR_FENCE;
	public static final DeferredItem<Item> NACOR_FENCE_GATE;
	public static final DeferredItem<Item> NACOR_PRESSURE_PLATE;
	public static final DeferredItem<Item> NACOR_BUTTON;
	public static final DeferredItem<Item> NACOR_PICKAXE;
	public static final DeferredItem<Item> NACOR_AXE;
	public static final DeferredItem<Item> NACOR_SWORD;
	public static final DeferredItem<Item> NACOR_SHOVEL;
	public static final DeferredItem<Item> NACOR_HOE;
	public static final DeferredItem<Item> YETI_SPAWN_EGG;
	public static final DeferredItem<Item> SWORD_OF_THE_FROZEN_WARRIOR;
	public static final DeferredItem<Item> ICE_DRAGON_SPAWN_EGG;
	public static final DeferredItem<Item> ICE_DRAGON_ICEBALL;
	public static final DeferredItem<Item> YETI_HEART;
	public static final DeferredItem<Item> ICE_DRAGON_HEART;
	public static final DeferredItem<Item> ICEY_GRASS;
	public static final DeferredItem<Item> SKELETON_PICKAXE;
	public static final DeferredItem<Item> SKELETON_AXE;
	public static final DeferredItem<Item> SKELETON_SWORD;
	public static final DeferredItem<Item> SKELETON_SHOVEL;
	public static final DeferredItem<Item> SKELETON_HOE;
	public static final DeferredItem<Item> SKELETON_ARMOR_HELMET;
	public static final DeferredItem<Item> SKELETON_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SKELETON_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SKELETON_ARMOR_BOOTS;
	public static final DeferredItem<Item> IGNIGHTIUM_INGOT;
	public static final DeferredItem<Item> IGNIGHTIUM_ORE;
	public static final DeferredItem<Item> IGNIGHTIUM_BLOCK;
	public static final DeferredItem<Item> IGNIGHTIUM_PICKAXE;
	public static final DeferredItem<Item> IGNIGHTIUM_AXE;
	public static final DeferredItem<Item> IGNIGHTIUM_SWORD;
	public static final DeferredItem<Item> IGNIGHTIUM_SHOVEL;
	public static final DeferredItem<Item> IGNIGHTIUM_HOE;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> IGNIGHTIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> BRAIN_FLUID_BUCKET;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_HELMET;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> COMMAND_BLOCK_ARMOR_BOOTS;
	public static final DeferredItem<Item> COMMAND_BLOCK_PICKAXE;
	public static final DeferredItem<Item> COMMAND_BLOCK_AXE;
	public static final DeferredItem<Item> COMMAND_BLOCK_SWORD;
	public static final DeferredItem<Item> COMMAND_BLOCK_SHOVEL;
	public static final DeferredItem<Item> COMMAND_BLOCK_HOE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_HELMET;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_ARMOR_BOOTS;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_PICKAXE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_AXE;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_SWORD;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_SHOVEL;
	public static final DeferredItem<Item> CHAIN_COMMAND_BLOCK_HOE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_HELMET;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_ARMOR_BOOTS;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_PICKAXE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_AXE;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_SWORD;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_SHOVEL;
	public static final DeferredItem<Item> REPEATING_COMMAND_BLOCK_HOE;
	public static final DeferredItem<Item> MASTER_OF_THE_DARK_ARTS_SPAWN_EGG;
	public static final DeferredItem<Item> DARK_FLOWER;
	public static final DeferredItem<Item> ICE_PILLAR;
	public static final DeferredItem<Item> DARK_SPLATTER;
	public static final DeferredItem<Item> DARK_COOKIE;
	public static final DeferredItem<Item> DARK_PHANTOM_SPAWN_EGG;
	public static final DeferredItem<Item> DARK_PARTICLE_ITEM;
	public static final DeferredItem<Item> BRICK_ARMOR_HELMET;
	public static final DeferredItem<Item> BRICK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BRICK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BRICK_ARMOR_BOOTS;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_HELMET;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> RESIN_BRICK_ARMOR_BOOTS;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_HELMET;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DEEPSLATE_BRICK_ARMOR_BOOTS;
	public static final DeferredItem<Item> IGNYITE;
	public static final DeferredItem<Item> STEEL;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_HELMET;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> STEEL_ARMOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> STEEL_TOOL_PICKAXE;
	public static final DeferredItem<Item> STEEL_TOOL_AXE;
	public static final DeferredItem<Item> STEEL_TOOL_SWORD;
	public static final DeferredItem<Item> STEEL_TOOL_SHOVEL;
	public static final DeferredItem<Item> STEEL_TOOL_HOE;
	public static final DeferredItem<Item> CAPSTEEL;
	public static final DeferredItem<Item> REFINED_FLINT_AND_STEEL;
	public static final DeferredItem<Item> REBOUNDED_FIRE;
	public static final DeferredItem<Item> MOLTEN_METAL;
	public static final DeferredItem<Item> VERY_MOLTEN_METAL;
	public static final DeferredItem<Item> BLOCK_OF_FLINT;
	public static final DeferredItem<Item> WARTED_EMERALD;
	public static final DeferredItem<Item> THE_WILL_OF_RIGHTS;
	public static final DeferredItem<Item> WALKING_CHEST_SPAWN_EGG;
	public static final DeferredItem<Item> BRANITE;
	public static final DeferredItem<Item> BRANITE_ORE;
	public static final DeferredItem<Item> BRANITE_LUNGE;
	public static final DeferredItem<Item> BULL_SPAWN_EGG;
	public static final DeferredItem<Item> STONE_LUNGE;
	public static final DeferredItem<Item> AMETHESIUM_ORE;
	public static final DeferredItem<Item> AMETHESIUM_INGOT;
	public static final DeferredItem<Item> AMETHESIUM_PICKAXE;
	public static final DeferredItem<Item> AMETHESIUM_AXE;
	public static final DeferredItem<Item> AMETHESIUM_SWORD;
	public static final DeferredItem<Item> AMETHESIUM_SHOVEL;
	public static final DeferredItem<Item> AMETHESIUM_HOE;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AMETHESIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> AMETHESIUM_LUNGE;
	public static final DeferredItem<Item> CUBER_SPAWN_EGG;
	public static final DeferredItem<Item> CUBE_ESSENCE;
	static {
		COAL_PICKAXE = register("coal_pickaxe", CoalPickaxeItem::new);
		ENDER_HELMET_HELMET = register("ender_helmet_helmet", EnderHelmetItem.Helmet::new);
		ACID_ARMOR_HELMET = register("acid_armor_helmet", AcidArmorItem.Helmet::new);
		ACID_ARMOR_CHESTPLATE = register("acid_armor_chestplate", AcidArmorItem.Chestplate::new);
		ACID_ARMOR_LEGGINGS = register("acid_armor_leggings", AcidArmorItem.Leggings::new);
		ACID_ARMOR_BOOTS = register("acid_armor_boots", AcidArmorItem.Boots::new);
		ACID_FLUID_BUCKET = register("acid_fluid_bucket", AcidFluidItem::new);
		DINAMITE = register("dinamite", DinamiteItem::new);
		WASTE_BLOCK = block(BigAddonModBlocks.WASTE_BLOCK);
		WASTE_STONE = block(BigAddonModBlocks.WASTE_STONE);
		WASTE_LOG = block(BigAddonModBlocks.WASTE_LOG);
		WASTE_LEAVES = block(BigAddonModBlocks.WASTE_LEAVES);
		WASTE = register("waste", WasteItem::new);
		URAINIUM_CHUNK = block(BigAddonModBlocks.URAINIUM_CHUNK);
		URAINIUM_PEICE = register("urainium_peice", UrainiumPeiceItem::new);
		URAINIUM_INGOT = register("urainium_ingot", UrainiumIngotItem::new);
		URAINIUM_BLADE = register("urainium_blade", UrainiumBladeItem::new);
		URAINIUM_PICKAXE = register("urainium_pickaxe", UrainiumPickaxeItem::new);
		URAINIUM_SHIELD = register("urainium_shield", UrainiumShieldItem::new);
		DIRT_ARMOR_HELMET = register("dirt_armor_helmet", DirtArmorItem.Helmet::new);
		DIRT_ARMOR_CHESTPLATE = register("dirt_armor_chestplate", DirtArmorItem.Chestplate::new);
		DIRT_ARMOR_LEGGINGS = register("dirt_armor_leggings", DirtArmorItem.Leggings::new);
		DIRT_ARMOR_BOOTS = register("dirt_armor_boots", DirtArmorItem.Boots::new);
		GRAVITE = block(BigAddonModBlocks.GRAVITE);
		ORACLE = register("oracle", OracleItem::new);
		SEMITE = block(BigAddonModBlocks.SEMITE);
		FORGIUM_ORE = block(BigAddonModBlocks.FORGIUM_ORE);
		FORGIUM = register("forgium", ForgiumItem::new);
		FORGIUM_MULTITOOL = register("forgium_multitool", ForgiumMultitoolItem::new);
		MOLDELER = block(BigAddonModBlocks.MOLDELER);
		CAPSULE = block(BigAddonModBlocks.CAPSULE);
		CAPSULED_REDSTONE_BLOCK = block(BigAddonModBlocks.CAPSULED_REDSTONE_BLOCK);
		LONG_ZOMBIE_SPAWN_EGG = register("long_zombie_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.LONG_ZOMBIE.get(), properties));
		TITAN_SPAWN_EGG = register("titan_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.TITAN.get(), properties));
		TITAN_HEART = register("titan_heart", TitanHeartItem::new);
		TITAN_INGOT = register("titan_ingot", TitanIngotItem::new);
		TITAN_ARMOR_ARMOR_HELMET = register("titan_armor_armor_helmet", TitanArmorArmorItem.Helmet::new);
		TITAN_ARMOR_ARMOR_CHESTPLATE = register("titan_armor_armor_chestplate", TitanArmorArmorItem.Chestplate::new);
		TITAN_ARMOR_ARMOR_LEGGINGS = register("titan_armor_armor_leggings", TitanArmorArmorItem.Leggings::new);
		TITAN_ARMOR_ARMOR_BOOTS = register("titan_armor_armor_boots", TitanArmorArmorItem.Boots::new);
		HEVORE = block(BigAddonModBlocks.HEVORE);
		TITAN_TOOL_PICKAXE = register("titan_tool_pickaxe", TitanToolPickaxeItem::new);
		TITAN_TOOL_AXE = register("titan_tool_axe", TitanToolAxeItem::new);
		TITAN_TOOL_SWORD = register("titan_tool_sword", TitanToolSwordItem::new);
		FAIRY_SPAWN_EGG = register("fairy_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.FAIRY.get(), properties));
		BLOCK_OF_SPARKLES = block(BigAddonModBlocks.BLOCK_OF_SPARKLES);
		PROD_SPAWN_EGG = register("prod_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.PROD.get(), properties));
		PROD_MISSLE_ITEM = register("prod_missle_item", ProdMissleItemItem::new);
		SPARKLES = register("sparkles", SparklesItem::new);
		FAIRY_HEART = register("fairy_heart", FairyHeartItem::new);
		SPARKLE_PICKAXE = register("sparkle_pickaxe", SparklePickaxeItem::new);
		SPARKLE_AXE = register("sparkle_axe", SparkleAxeItem::new);
		SPARKLE_SWORD = register("sparkle_sword", SparkleSwordItem::new);
		ENERGY_DETECTOR = register("energy_detector", EnergyDetectorItem::new);
		GYRULE_ORE = block(BigAddonModBlocks.GYRULE_ORE);
		GYRULE_CRYSTAL = register("gyrule_crystal", GyruleCrystalItem::new);
		ANDOR_WOOD = block(BigAddonModBlocks.ANDOR_WOOD);
		ANDOR_LOG = block(BigAddonModBlocks.ANDOR_LOG);
		ANDOR_PLANKS = block(BigAddonModBlocks.ANDOR_PLANKS);
		ANDOR_LEAVES = block(BigAddonModBlocks.ANDOR_LEAVES);
		ANDOR_STAIRS = block(BigAddonModBlocks.ANDOR_STAIRS);
		ANDOR_SLAB = block(BigAddonModBlocks.ANDOR_SLAB);
		ANDOR_FENCE = block(BigAddonModBlocks.ANDOR_FENCE);
		ANDOR_FENCE_GATE = block(BigAddonModBlocks.ANDOR_FENCE_GATE);
		ANDOR_PRESSURE_PLATE = block(BigAddonModBlocks.ANDOR_PRESSURE_PLATE);
		ANDOR_BUTTON = block(BigAddonModBlocks.ANDOR_BUTTON);
		ANDOR_ARMOR_HELMET = register("andor_armor_helmet", AndorArmorItem.Helmet::new);
		ANDOR_ARMOR_CHESTPLATE = register("andor_armor_chestplate", AndorArmorItem.Chestplate::new);
		ANDOR_ARMOR_LEGGINGS = register("andor_armor_leggings", AndorArmorItem.Leggings::new);
		ANDOR_ARMOR_BOOTS = register("andor_armor_boots", AndorArmorItem.Boots::new);
		ANDOR_PICKAXE = register("andor_pickaxe", AndorPickaxeItem::new);
		ANDOR_AXE = register("andor_axe", AndorAxeItem::new);
		ANDOR_SWORD = register("andor_sword", AndorSwordItem::new);
		ANDOR_SHOVEL = register("andor_shovel", AndorShovelItem::new);
		ANDOR_HOE = register("andor_hoe", AndorHoeItem::new);
		SUGAR_ENTITY_SPAWN_EGG = register("sugar_entity_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.SUGAR_ENTITY.get(), properties));
		FERTILIZED_SUGAR = register("fertilized_sugar", FertilizedSugarItem::new);
		DIRT_TOOL_PICKAXE = register("dirt_tool_pickaxe", DirtToolPickaxeItem::new);
		DIRT_TOOL_AXE = register("dirt_tool_axe", DirtToolAxeItem::new);
		DIRT_TOOL_SWORD = register("dirt_tool_sword", DirtToolSwordItem::new);
		DIRT_TOOL_SHOVEL = register("dirt_tool_shovel", DirtToolShovelItem::new);
		DIRT_TOOL_HOE = register("dirt_tool_hoe", DirtToolHoeItem::new);
		ANDESITE_PICKAXE = register("andesite_pickaxe", AndesitePickaxeItem::new);
		ANDESITE_AXE = register("andesite_axe", AndesiteAxeItem::new);
		ANDESITE_SWORD = register("andesite_sword", AndesiteSwordItem::new);
		ANDESITE_SHOVEL = register("andesite_shovel", AndesiteShovelItem::new);
		ANDESITE_HOE = register("andesite_hoe", AndesiteHoeItem::new);
		GRANITE_ARMOR_HELMET = register("granite_armor_helmet", GraniteArmorItem.Helmet::new);
		GRANITE_ARMOR_CHESTPLATE = register("granite_armor_chestplate", GraniteArmorItem.Chestplate::new);
		GRANITE_ARMOR_LEGGINGS = register("granite_armor_leggings", GraniteArmorItem.Leggings::new);
		GRANITE_ARMOR_BOOTS = register("granite_armor_boots", GraniteArmorItem.Boots::new);
		YELLOW_DIRT = block(BigAddonModBlocks.YELLOW_DIRT);
		YELLOW_GRASS_BLOCK = block(BigAddonModBlocks.YELLOW_GRASS_BLOCK);
		BLAZITE = register("blazite", BlaziteItem::new);
		BLAZITE_ORE = block(BigAddonModBlocks.BLAZITE_ORE);
		BLAZITE_BLOCK = block(BigAddonModBlocks.BLAZITE_BLOCK);
		BLAZITE_PICKAXE = register("blazite_pickaxe", BlazitePickaxeItem::new);
		BLAZITE_AXE = register("blazite_axe", BlaziteAxeItem::new);
		BLAZITE_SWORD = register("blazite_sword", BlaziteSwordItem::new);
		BLAZITE_SHOVEL = register("blazite_shovel", BlaziteShovelItem::new);
		BLAZITE_HOE = register("blazite_hoe", BlaziteHoeItem::new);
		BLAZITE_ARMOR_HELMET = register("blazite_armor_helmet", BlaziteArmorItem.Helmet::new);
		BLAZITE_ARMOR_CHESTPLATE = register("blazite_armor_chestplate", BlaziteArmorItem.Chestplate::new);
		BLAZITE_ARMOR_LEGGINGS = register("blazite_armor_leggings", BlaziteArmorItem.Leggings::new);
		BLAZITE_ARMOR_BOOTS = register("blazite_armor_boots", BlaziteArmorItem.Boots::new);
		BRAIN = block(BigAddonModBlocks.BRAIN);
		BIRD_BRAIN_SPAWN_EGG = register("bird_brain_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.BIRD_BRAIN.get(), properties));
		STONE_ARMOR_HELMET = register("stone_armor_helmet", StoneArmorItem.Helmet::new);
		STONE_ARMOR_CHESTPLATE = register("stone_armor_chestplate", StoneArmorItem.Chestplate::new);
		STONE_ARMOR_LEGGINGS = register("stone_armor_leggings", StoneArmorItem.Leggings::new);
		STONE_ARMOR_BOOTS = register("stone_armor_boots", StoneArmorItem.Boots::new);
		COOKIE = register("cookie", CookieItem::new);
		SUGAR_COOKIE = register("sugar_cookie", SugarCookieItem::new);
		WOOL_ARMOR_HELMET = register("wool_armor_helmet", WoolArmorItem.Helmet::new);
		WOOL_ARMOR_CHESTPLATE = register("wool_armor_chestplate", WoolArmorItem.Chestplate::new);
		WOOL_ARMOR_LEGGINGS = register("wool_armor_leggings", WoolArmorItem.Leggings::new);
		WOOL_ARMOR_BOOTS = register("wool_armor_boots", WoolArmorItem.Boots::new);
		ANDESITE_ARMOR_HELMET = register("andesite_armor_helmet", AndesiteArmorItem.Helmet::new);
		ANDESITE_ARMOR_CHESTPLATE = register("andesite_armor_chestplate", AndesiteArmorItem.Chestplate::new);
		ANDESITE_ARMOR_LEGGINGS = register("andesite_armor_leggings", AndesiteArmorItem.Leggings::new);
		ANDESITE_ARMOR_BOOTS = register("andesite_armor_boots", AndesiteArmorItem.Boots::new);
		GRANITE_PICKAXE = register("granite_pickaxe", GranitePickaxeItem::new);
		GRANITE_AXE = register("granite_axe", GraniteAxeItem::new);
		GRANITE_SWORD = register("granite_sword", GraniteSwordItem::new);
		GRANITE_SHOVEL = register("granite_shovel", GraniteShovelItem::new);
		GRANITE_HOE = register("granite_hoe", GraniteHoeItem::new);
		WOOL_PICKAXE = register("wool_pickaxe", WoolPickaxeItem::new);
		WOOL_AXE = register("wool_axe", WoolAxeItem::new);
		WOOL_SWORD = register("wool_sword", WoolSwordItem::new);
		WOOL_SHOVEL = register("wool_shovel", WoolShovelItem::new);
		WOOL_HOE = register("wool_hoe", WoolHoeItem::new);
		BRAIN_ARMOR_ARMOR_HELMET = register("brain_armor_armor_helmet", BrainArmorArmorItem.Helmet::new);
		BRAIN_ARMOR_ARMOR_CHESTPLATE = register("brain_armor_armor_chestplate", BrainArmorArmorItem.Chestplate::new);
		BRAIN_ARMOR_ARMOR_LEGGINGS = register("brain_armor_armor_leggings", BrainArmorArmorItem.Leggings::new);
		BRAIN_ARMOR_ARMOR_BOOTS = register("brain_armor_armor_boots", BrainArmorArmorItem.Boots::new);
		CAREFREE = register("carefree", CarefreeItem::new);
		HEROIC_DIAMOND = register("heroic_diamond", HeroicDiamondItem::new);
		TRASH_BAG = register("trash_bag", TrashBagItem::new);
		DARK_BAT_SPAWN_EGG = register("dark_bat_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.DARK_BAT.get(), properties));
		DARK_BAT_WING = register("dark_bat_wing", DarkBatWingItem::new);
		DARK_BAT_SHEILD = register("dark_bat_sheild", DarkBatSheildItem::new);
		THIEF_SPAWN_EGG = register("thief_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.THIEF.get(), properties));
		APPLE_PIE = register("apple_pie", ApplePieItem::new);
		GREEN_SAND = block(BigAddonModBlocks.GREEN_SAND);
		GREEN_SANDSTONE = block(BigAddonModBlocks.GREEN_SANDSTONE);
		SMOOTH_GREEN_SANDSTONE = block(BigAddonModBlocks.SMOOTH_GREEN_SANDSTONE);
		BRAIN_FOOD = register("brain_food", BrainFoodItem::new);
		RADIANT_ZOMBIE_SPAWN_EGG = register("radiant_zombie_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.RADIANT_ZOMBIE.get(), properties));
		FROZEN_GRAVITE = block(BigAddonModBlocks.FROZEN_GRAVITE);
		NACOR_WOOD = block(BigAddonModBlocks.NACOR_WOOD);
		NACOR_LOG = block(BigAddonModBlocks.NACOR_LOG);
		NACOR_PLANKS = block(BigAddonModBlocks.NACOR_PLANKS);
		NACOR_LEAVES = block(BigAddonModBlocks.NACOR_LEAVES);
		NACOR_STAIRS = block(BigAddonModBlocks.NACOR_STAIRS);
		NACOR_SLAB = block(BigAddonModBlocks.NACOR_SLAB);
		NACOR_FENCE = block(BigAddonModBlocks.NACOR_FENCE);
		NACOR_FENCE_GATE = block(BigAddonModBlocks.NACOR_FENCE_GATE);
		NACOR_PRESSURE_PLATE = block(BigAddonModBlocks.NACOR_PRESSURE_PLATE);
		NACOR_BUTTON = block(BigAddonModBlocks.NACOR_BUTTON);
		NACOR_PICKAXE = register("nacor_pickaxe", NacorPickaxeItem::new);
		NACOR_AXE = register("nacor_axe", NacorAxeItem::new);
		NACOR_SWORD = register("nacor_sword", NacorSwordItem::new);
		NACOR_SHOVEL = register("nacor_shovel", NacorShovelItem::new);
		NACOR_HOE = register("nacor_hoe", NacorHoeItem::new);
		YETI_SPAWN_EGG = register("yeti_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.YETI.get(), properties));
		SWORD_OF_THE_FROZEN_WARRIOR = register("sword_of_the_frozen_warrior", SwordOfTheFrozenWarriorItem::new);
		ICE_DRAGON_SPAWN_EGG = register("ice_dragon_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.ICE_DRAGON.get(), properties));
		ICE_DRAGON_ICEBALL = register("ice_dragon_iceball", IceDragonIceballItem::new);
		YETI_HEART = register("yeti_heart", YetiHeartItem::new);
		ICE_DRAGON_HEART = register("ice_dragon_heart", IceDragonHeartItem::new);
		ICEY_GRASS = block(BigAddonModBlocks.ICEY_GRASS);
		SKELETON_PICKAXE = register("skeleton_pickaxe", SkeletonPickaxeItem::new);
		SKELETON_AXE = register("skeleton_axe", SkeletonAxeItem::new);
		SKELETON_SWORD = register("skeleton_sword", SkeletonSwordItem::new);
		SKELETON_SHOVEL = register("skeleton_shovel", SkeletonShovelItem::new);
		SKELETON_HOE = register("skeleton_hoe", SkeletonHoeItem::new);
		SKELETON_ARMOR_HELMET = register("skeleton_armor_helmet", SkeletonArmorItem.Helmet::new);
		SKELETON_ARMOR_CHESTPLATE = register("skeleton_armor_chestplate", SkeletonArmorItem.Chestplate::new);
		SKELETON_ARMOR_LEGGINGS = register("skeleton_armor_leggings", SkeletonArmorItem.Leggings::new);
		SKELETON_ARMOR_BOOTS = register("skeleton_armor_boots", SkeletonArmorItem.Boots::new);
		IGNIGHTIUM_INGOT = register("ignightium_ingot", IgnightiumIngotItem::new);
		IGNIGHTIUM_ORE = block(BigAddonModBlocks.IGNIGHTIUM_ORE);
		IGNIGHTIUM_BLOCK = block(BigAddonModBlocks.IGNIGHTIUM_BLOCK);
		IGNIGHTIUM_PICKAXE = register("ignightium_pickaxe", IgnightiumPickaxeItem::new);
		IGNIGHTIUM_AXE = register("ignightium_axe", IgnightiumAxeItem::new);
		IGNIGHTIUM_SWORD = register("ignightium_sword", IgnightiumSwordItem::new);
		IGNIGHTIUM_SHOVEL = register("ignightium_shovel", IgnightiumShovelItem::new);
		IGNIGHTIUM_HOE = register("ignightium_hoe", IgnightiumHoeItem::new);
		IGNIGHTIUM_ARMOR_HELMET = register("ignightium_armor_helmet", IgnightiumArmorItem.Helmet::new);
		IGNIGHTIUM_ARMOR_CHESTPLATE = register("ignightium_armor_chestplate", IgnightiumArmorItem.Chestplate::new);
		IGNIGHTIUM_ARMOR_LEGGINGS = register("ignightium_armor_leggings", IgnightiumArmorItem.Leggings::new);
		IGNIGHTIUM_ARMOR_BOOTS = register("ignightium_armor_boots", IgnightiumArmorItem.Boots::new);
		BRAIN_FLUID_BUCKET = register("brain_fluid_bucket", BrainFluidItem::new);
		COMMAND_BLOCK_ARMOR_HELMET = register("command_block_armor_helmet", CommandBlockArmorItem.Helmet::new);
		COMMAND_BLOCK_ARMOR_CHESTPLATE = register("command_block_armor_chestplate", CommandBlockArmorItem.Chestplate::new);
		COMMAND_BLOCK_ARMOR_LEGGINGS = register("command_block_armor_leggings", CommandBlockArmorItem.Leggings::new);
		COMMAND_BLOCK_ARMOR_BOOTS = register("command_block_armor_boots", CommandBlockArmorItem.Boots::new);
		COMMAND_BLOCK_PICKAXE = register("command_block_pickaxe", CommandBlockPickaxeItem::new);
		COMMAND_BLOCK_AXE = register("command_block_axe", CommandBlockAxeItem::new);
		COMMAND_BLOCK_SWORD = register("command_block_sword", CommandBlockSwordItem::new);
		COMMAND_BLOCK_SHOVEL = register("command_block_shovel", CommandBlockShovelItem::new);
		COMMAND_BLOCK_HOE = register("command_block_hoe", CommandBlockHoeItem::new);
		CHAIN_COMMAND_BLOCK_ARMOR_HELMET = register("chain_command_block_armor_helmet", ChainCommandBlockArmorItem.Helmet::new);
		CHAIN_COMMAND_BLOCK_ARMOR_CHESTPLATE = register("chain_command_block_armor_chestplate", ChainCommandBlockArmorItem.Chestplate::new);
		CHAIN_COMMAND_BLOCK_ARMOR_LEGGINGS = register("chain_command_block_armor_leggings", ChainCommandBlockArmorItem.Leggings::new);
		CHAIN_COMMAND_BLOCK_ARMOR_BOOTS = register("chain_command_block_armor_boots", ChainCommandBlockArmorItem.Boots::new);
		CHAIN_COMMAND_BLOCK_PICKAXE = register("chain_command_block_pickaxe", ChainCommandBlockPickaxeItem::new);
		CHAIN_COMMAND_BLOCK_AXE = register("chain_command_block_axe", ChainCommandBlockAxeItem::new);
		CHAIN_COMMAND_BLOCK_SWORD = register("chain_command_block_sword", ChainCommandBlockSwordItem::new);
		CHAIN_COMMAND_BLOCK_SHOVEL = register("chain_command_block_shovel", ChainCommandBlockShovelItem::new);
		CHAIN_COMMAND_BLOCK_HOE = register("chain_command_block_hoe", ChainCommandBlockHoeItem::new);
		REPEATING_COMMAND_BLOCK_ARMOR_HELMET = register("repeating_command_block_armor_helmet", RepeatingCommandBlockArmorItem.Helmet::new);
		REPEATING_COMMAND_BLOCK_ARMOR_CHESTPLATE = register("repeating_command_block_armor_chestplate", RepeatingCommandBlockArmorItem.Chestplate::new);
		REPEATING_COMMAND_BLOCK_ARMOR_LEGGINGS = register("repeating_command_block_armor_leggings", RepeatingCommandBlockArmorItem.Leggings::new);
		REPEATING_COMMAND_BLOCK_ARMOR_BOOTS = register("repeating_command_block_armor_boots", RepeatingCommandBlockArmorItem.Boots::new);
		REPEATING_COMMAND_BLOCK_PICKAXE = register("repeating_command_block_pickaxe", RepeatingCommandBlockPickaxeItem::new);
		REPEATING_COMMAND_BLOCK_AXE = register("repeating_command_block_axe", RepeatingCommandBlockAxeItem::new);
		REPEATING_COMMAND_BLOCK_SWORD = register("repeating_command_block_sword", RepeatingCommandBlockSwordItem::new);
		REPEATING_COMMAND_BLOCK_SHOVEL = register("repeating_command_block_shovel", RepeatingCommandBlockShovelItem::new);
		REPEATING_COMMAND_BLOCK_HOE = register("repeating_command_block_hoe", RepeatingCommandBlockHoeItem::new);
		MASTER_OF_THE_DARK_ARTS_SPAWN_EGG = register("master_of_the_dark_arts_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.MASTER_OF_THE_DARK_ARTS.get(), properties));
		DARK_FLOWER = block(BigAddonModBlocks.DARK_FLOWER);
		ICE_PILLAR = block(BigAddonModBlocks.ICE_PILLAR);
		DARK_SPLATTER = register("dark_splatter", DarkSplatterItem::new);
		DARK_COOKIE = register("dark_cookie", DarkCookieItem::new);
		DARK_PHANTOM_SPAWN_EGG = register("dark_phantom_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.DARK_PHANTOM.get(), properties));
		DARK_PARTICLE_ITEM = register("dark_particle_item", DarkParticleItemItem::new);
		BRICK_ARMOR_HELMET = register("brick_armor_helmet", BrickArmorItem.Helmet::new);
		BRICK_ARMOR_CHESTPLATE = register("brick_armor_chestplate", BrickArmorItem.Chestplate::new);
		BRICK_ARMOR_LEGGINGS = register("brick_armor_leggings", BrickArmorItem.Leggings::new);
		BRICK_ARMOR_BOOTS = register("brick_armor_boots", BrickArmorItem.Boots::new);
		RESIN_BRICK_ARMOR_HELMET = register("resin_brick_armor_helmet", ResinBrickArmorItem.Helmet::new);
		RESIN_BRICK_ARMOR_CHESTPLATE = register("resin_brick_armor_chestplate", ResinBrickArmorItem.Chestplate::new);
		RESIN_BRICK_ARMOR_LEGGINGS = register("resin_brick_armor_leggings", ResinBrickArmorItem.Leggings::new);
		RESIN_BRICK_ARMOR_BOOTS = register("resin_brick_armor_boots", ResinBrickArmorItem.Boots::new);
		DEEPSLATE_BRICK_ARMOR_HELMET = register("deepslate_brick_armor_helmet", DeepslateBrickArmorItem.Helmet::new);
		DEEPSLATE_BRICK_ARMOR_CHESTPLATE = register("deepslate_brick_armor_chestplate", DeepslateBrickArmorItem.Chestplate::new);
		DEEPSLATE_BRICK_ARMOR_LEGGINGS = register("deepslate_brick_armor_leggings", DeepslateBrickArmorItem.Leggings::new);
		DEEPSLATE_BRICK_ARMOR_BOOTS = register("deepslate_brick_armor_boots", DeepslateBrickArmorItem.Boots::new);
		IGNYITE = block(BigAddonModBlocks.IGNYITE);
		STEEL = register("steel", SteelItem::new);
		STEEL_ARMOR_ARMOR_HELMET = register("steel_armor_armor_helmet", SteelArmorArmorItem.Helmet::new);
		STEEL_ARMOR_ARMOR_CHESTPLATE = register("steel_armor_armor_chestplate", SteelArmorArmorItem.Chestplate::new);
		STEEL_ARMOR_ARMOR_LEGGINGS = register("steel_armor_armor_leggings", SteelArmorArmorItem.Leggings::new);
		STEEL_ARMOR_ARMOR_BOOTS = register("steel_armor_armor_boots", SteelArmorArmorItem.Boots::new);
		STEEL_TOOL_PICKAXE = register("steel_tool_pickaxe", SteelToolPickaxeItem::new);
		STEEL_TOOL_AXE = register("steel_tool_axe", SteelToolAxeItem::new);
		STEEL_TOOL_SWORD = register("steel_tool_sword", SteelToolSwordItem::new);
		STEEL_TOOL_SHOVEL = register("steel_tool_shovel", SteelToolShovelItem::new);
		STEEL_TOOL_HOE = register("steel_tool_hoe", SteelToolHoeItem::new);
		CAPSTEEL = register("capsteel", CapsteelItem::new);
		REFINED_FLINT_AND_STEEL = register("refined_flint_and_steel", RefinedFlintAndSteelItem::new);
		REBOUNDED_FIRE = block(BigAddonModBlocks.REBOUNDED_FIRE);
		MOLTEN_METAL = register("molten_metal", MoltenMetalItem::new);
		VERY_MOLTEN_METAL = register("very_molten_metal", VeryMoltenMetalItem::new);
		BLOCK_OF_FLINT = block(BigAddonModBlocks.BLOCK_OF_FLINT);
		WARTED_EMERALD = register("warted_emerald", WartedEmeraldItem::new);
		THE_WILL_OF_RIGHTS = register("the_will_of_rights", TheWillOfRightsItem::new);
		WALKING_CHEST_SPAWN_EGG = register("walking_chest_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.WALKING_CHEST.get(), properties));
		BRANITE = register("branite", BraniteItem::new);
		BRANITE_ORE = block(BigAddonModBlocks.BRANITE_ORE, new Item.Properties().rarity(Rarity.UNCOMMON));
		BRANITE_LUNGE = register("branite_lunge", BraniteLungeItem::new);
		BULL_SPAWN_EGG = register("bull_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.BULL.get(), properties));
		STONE_LUNGE = register("stone_lunge", StoneLungeItem::new);
		AMETHESIUM_ORE = block(BigAddonModBlocks.AMETHESIUM_ORE, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant());
		AMETHESIUM_INGOT = register("amethesium_ingot", AmethesiumIngotItem::new);
		AMETHESIUM_PICKAXE = register("amethesium_pickaxe", AmethesiumPickaxeItem::new);
		AMETHESIUM_AXE = register("amethesium_axe", AmethesiumAxeItem::new);
		AMETHESIUM_SWORD = register("amethesium_sword", AmethesiumSwordItem::new);
		AMETHESIUM_SHOVEL = register("amethesium_shovel", AmethesiumShovelItem::new);
		AMETHESIUM_HOE = register("amethesium_hoe", AmethesiumHoeItem::new);
		AMETHESIUM_ARMOR_HELMET = register("amethesium_armor_helmet", AmethesiumArmorItem.Helmet::new);
		AMETHESIUM_ARMOR_CHESTPLATE = register("amethesium_armor_chestplate", AmethesiumArmorItem.Chestplate::new);
		AMETHESIUM_ARMOR_LEGGINGS = register("amethesium_armor_leggings", AmethesiumArmorItem.Leggings::new);
		AMETHESIUM_ARMOR_BOOTS = register("amethesium_armor_boots", AmethesiumArmorItem.Boots::new);
		AMETHESIUM_LUNGE = register("amethesium_lunge", AmethesiumLungeItem::new);
		CUBER_SPAWN_EGG = register("cuber_spawn_egg", properties -> new SpawnEggItem(BigAddonModEntities.CUBER.get(), properties));
		CUBE_ESSENCE = register("cube_essence", CubeEssenceItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new TrashBagInventoryCapability(stack), TRASH_BAG.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), ACID_FLUID_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), BRAIN_FLUID_BUCKET.get());
	}
}